SITE = {
    "name": "ToolMint",
    "tagline": "Fast, private browser tools that work without uploads or logins.",
    "description": "ToolMint is a privacy-friendly collection of online utilities for text, developer data, images, and everyday calculators. Most tools run directly in your browser for speed, privacy, and zero server cost.",
    "base_url": "https://example.pages.dev",
    "email": "rishibanota837@gmail.com",
    "brand_color": "#6d5efc",
    "categories": [
        {
            "id": "developer",
            "name": "Developer & Data",
            "description": "Format, convert, and inspect JSON, CSV, URLs, hashes, JWTs, and timestamps.",
        },
        {
            "id": "text",
            "name": "Text Utilities",
            "description": "Encode, decode, clean, and transform text quickly in your browser.",
        },
        {
            "id": "image",
            "name": "Image Utilities",
            "description": "Resize, convert, and preview images without sending files to a server.",
        },
        {
            "id": "calculators",
            "name": "Calculators",
            "description": "Simple everyday calculators for GST, EMI, percentages, and dates.",
        },
    ],
}

TOOLS = [
    {
        "id": "json-formatter",
        "slug": "json-formatter",
        "title": "JSON Formatter",
        "category": "developer",
        "icon": "{}",
        "type": "text",
        "summary": "Beautify and validate JSON instantly in your browser.",
        "seo_title": "JSON Formatter Online - Beautify and Validate JSON Privately",
        "meta_description": "Format, validate, and beautify JSON online with a clean privacy-friendly tool.",
        "keywords": ["json formatter", "json beautifier", "json validator online"],
        "how_to": [
            "Paste raw JSON into the input box.",
            "Click format to validate and beautify the structure.",
            "Copy the result or download it as a file.",
        ],
        "faq": [
            (
                "Is my JSON uploaded?",
                "No. The formatter runs in your browser and does not send your JSON to the server.",
            ),
            (
                "Can it validate broken JSON?",
                "Yes. The tool shows a friendly error if the JSON is invalid.",
            ),
        ],
        "related": ["json-to-csv", "csv-to-json", "jwt-decoder"],
    },
    {
        "id": "json-to-csv",
        "slug": "json-to-csv",
        "title": "JSON to CSV Converter",
        "category": "developer",
        "icon": "⇄",
        "type": "text",
        "summary": "Convert arrays of JSON objects into CSV for spreadsheets.",
        "seo_title": "JSON to CSV Converter Online - Browser Based",
        "meta_description": "Convert JSON arrays to CSV online without uploads. Fast local conversion for spreadsheet-friendly exports.",
        "keywords": ["json to csv", "convert json array to csv", "csv export tool"],
        "how_to": [
            "Paste a JSON array containing objects.",
            "Click convert to create a CSV table.",
            "Copy or download the CSV output.",
        ],
        "faq": [
            (
                "What JSON shape works best?",
                'This tool works best with an array of flat objects such as [{"name":"A"},{"name":"B"}].',
            ),
            (
                "Can it handle nested objects?",
                "Nested values are flattened into dot notation where possible.",
            ),
        ],
        "related": ["csv-to-json", "json-formatter", "base64-encoder"],
    },
    {
        "id": "csv-to-json",
        "slug": "csv-to-json",
        "title": "CSV to JSON Converter",
        "category": "developer",
        "icon": "⎘",
        "type": "text",
        "summary": "Turn CSV rows into JSON objects quickly with header support.",
        "seo_title": "CSV to JSON Converter Online - Clean Local Parsing",
        "meta_description": "Convert CSV data to JSON in your browser using a simple privacy-friendly CSV parser.",
        "keywords": ["csv to json", "csv parser", "spreadsheet to json"],
        "how_to": [
            "Paste CSV with a header row.",
            "Click convert to parse each row into JSON.",
            "Copy the output or download it as a .json file.",
        ],
        "faq": [
            (
                "Does the first row become keys?",
                "Yes. The first row is used as the property names for each JSON object.",
            ),
            (
                "Can it parse quoted CSV?",
                "Yes. Basic quoted fields and commas inside quoted text are supported.",
            ),
        ],
        "related": ["json-to-csv", "json-formatter", "url-encoder"],
    },
    {
        "id": "base64-encoder",
        "slug": "base64-encoder",
        "title": "Base64 Encoder",
        "category": "text",
        "icon": "64",
        "type": "text",
        "summary": "Encode plain text to Base64 locally in your browser.",
        "seo_title": "Base64 Encoder Online - Fast Client Side Encoding",
        "meta_description": "Encode text to Base64 instantly with a browser-based tool that keeps your data local.",
        "keywords": ["base64 encode", "text to base64", "base64 online"],
        "how_to": [
            "Type or paste plain text into the input area.",
            "Click encode to generate Base64 output.",
            "Copy the encoded value for reuse.",
        ],
        "faq": [
            ("Does it support Unicode?", "Yes. UTF-8 text is supported."),
            (
                "Is there any server processing?",
                "No. Encoding happens entirely in your browser.",
            ),
        ],
        "related": ["base64-decoder", "url-encoder", "sha256-generator"],
    },
    {
        "id": "base64-decoder",
        "slug": "base64-decoder",
        "title": "Base64 Decoder",
        "category": "text",
        "icon": "↺",
        "type": "text",
        "summary": "Decode Base64 back into readable text safely on your device.",
        "seo_title": "Base64 Decoder Online - Browser Based Decoder",
        "meta_description": "Decode Base64 text online using a clean privacy-first browser tool.",
        "keywords": ["base64 decode", "decode base64", "base64 text decoder"],
        "how_to": [
            "Paste a Base64 string into the input box.",
            "Click decode to restore the original text.",
            "Copy the output or continue editing it.",
        ],
        "faq": [
            (
                "What if the string is invalid?",
                "The tool will show a friendly error and leave your input unchanged.",
            ),
            (
                "Can I decode text copied from APIs?",
                "Yes. It is handy for tokens, payload samples, and encoded strings.",
            ),
        ],
        "related": ["base64-encoder", "jwt-decoder", "url-decoder"],
    },
    {
        "id": "url-encoder",
        "slug": "url-encoder",
        "title": "URL Encoder",
        "category": "developer",
        "icon": "%",
        "type": "text",
        "summary": "Encode URLs and query text for safer sharing and API usage.",
        "seo_title": "URL Encoder Online - Encode Query Strings Quickly",
        "meta_description": "Encode URLs, query parameters, and text for web-safe usage with this local browser tool.",
        "keywords": ["url encode", "query string encoder", "percent encode online"],
        "how_to": [
            "Paste your raw URL or text.",
            "Click encode to percent-encode reserved characters.",
            "Copy the safe URL output.",
        ],
        "faq": [
            (
                "Why would I use URL encoding?",
                "It helps make spaces and special characters safe inside query strings and URLs.",
            ),
            ("Does it handle full URLs and plain text?", "Yes. It works for both."),
        ],
        "related": ["url-decoder", "base64-encoder", "json-formatter"],
    },
    {
        "id": "url-decoder",
        "slug": "url-decoder",
        "title": "URL Decoder",
        "category": "developer",
        "icon": "↧",
        "type": "text",
        "summary": "Decode percent-encoded strings into human-readable text.",
        "seo_title": "URL Decoder Online - Decode Encoded URLs",
        "meta_description": "Decode encoded URLs and query values instantly in your browser.",
        "keywords": ["url decode", "percent decode", "decode query string"],
        "how_to": [
            "Paste an encoded URL or query parameter.",
            "Click decode to restore readable text.",
            "Copy the output or use it in another tool.",
        ],
        "faq": [
            (
                "Can it decode plus signs and spaces?",
                "Yes. It converts encoded values into normal readable text.",
            ),
            (
                "Will it alter my original text?",
                "No. Your original input remains in the input area.",
            ),
        ],
        "related": ["url-encoder", "base64-decoder", "csv-to-json"],
    },
    {
        "id": "case-converter",
        "slug": "case-converter",
        "title": "Text Case Converter",
        "category": "text",
        "icon": "Aa",
        "type": "text",
        "summary": "Convert text to upper, lower, title, sentence, or slug case.",
        "seo_title": "Text Case Converter Online - Uppercase, Lowercase, Title Case",
        "meta_description": "Convert text into uppercase, lowercase, title case, sentence case, and slug format instantly.",
        "keywords": [
            "case converter",
            "uppercase lowercase tool",
            "title case converter",
        ],
        "how_to": [
            "Paste any text into the editor.",
            "Choose the case style you want.",
            "Copy the converted result or continue editing it.",
        ],
        "faq": [
            (
                "Which case styles are included?",
                "Uppercase, lowercase, title case, sentence case, and slug case are included.",
            ),
            (
                "Can I use it for headlines and URLs?",
                "Yes. It works well for article titles, headings, and slug generation.",
            ),
        ],
        "related": ["slug-generator", "base64-encoder", "sha256-generator"],
    },
    {
        "id": "slug-generator",
        "slug": "slug-generator",
        "title": "Slug Generator",
        "category": "text",
        "icon": "//",
        "type": "text",
        "summary": "Turn a title or phrase into a clean SEO-friendly slug.",
        "seo_title": "Slug Generator Online - SEO Friendly URL Slugs",
        "meta_description": "Create clean URL slugs from titles and phrases in your browser without any uploads.",
        "keywords": ["slug generator", "url slug maker", "seo slug tool"],
        "how_to": [
            "Enter a title or phrase.",
            "Click generate to create a lowercase hyphenated slug.",
            "Copy it into your CMS, blog, or route name.",
        ],
        "faq": [
            (
                "Does it remove symbols?",
                "Yes. It removes most punctuation and converts spaces into hyphens.",
            ),
            (
                "Is it good for SEO?",
                "It helps produce short readable slugs, which are usually better for usability and SEO.",
            ),
        ],
        "related": ["case-converter", "url-encoder", "json-formatter"],
    },
    {
        "id": "sha256-generator",
        "slug": "sha256-generator",
        "title": "SHA-256 Hash Generator",
        "category": "developer",
        "icon": "#",
        "type": "text",
        "summary": "Generate SHA-256 hashes in your browser using the Web Crypto API.",
        "seo_title": "SHA-256 Hash Generator Online - Client Side Hashing",
        "meta_description": "Create SHA-256 hashes online in your browser using a private client-side tool.",
        "keywords": ["sha256 generator", "hash generator", "sha256 online"],
        "how_to": [
            "Paste the text you want to hash.",
            "Click generate hash.",
            "Copy the SHA-256 output for verification or development use.",
        ],
        "faq": [
            (
                "Can I reverse a SHA-256 hash?",
                "No. SHA-256 is a one-way hash function.",
            ),
            (
                "Does it use a library?",
                "It uses the browser's built-in Web Crypto API when available.",
            ),
        ],
        "related": ["jwt-decoder", "base64-encoder", "json-formatter"],
    },
    {
        "id": "jwt-decoder",
        "slug": "jwt-decoder",
        "title": "JWT Decoder",
        "category": "developer",
        "icon": "🔑",
        "type": "text",
        "summary": "Inspect JWT header and payload without sending tokens anywhere.",
        "seo_title": "JWT Decoder Online - Decode Header and Payload Locally",
        "meta_description": "Decode JWT header and payload privately in your browser with no server upload required.",
        "keywords": ["jwt decoder", "decode jwt online", "token payload viewer"],
        "how_to": [
            "Paste a JWT token into the input box.",
            "Click decode to read the header and payload.",
            "Review the structured JSON safely on your device.",
        ],
        "faq": [
            (
                "Does this verify signatures?",
                "No. It decodes the token structure but does not validate the signature.",
            ),
            (
                "Is the token sent to a server?",
                "No. Decoding happens entirely in your browser.",
            ),
        ],
        "related": ["json-formatter", "base64-decoder", "sha256-generator"],
    },
    {
        "id": "timestamp-converter",
        "slug": "timestamp-converter",
        "title": "Unix Timestamp Converter",
        "category": "developer",
        "icon": "⏱",
        "type": "text",
        "summary": "Convert Unix timestamps to local date/time and back again.",
        "seo_title": "Unix Timestamp Converter Online - Local Time and UTC",
        "meta_description": "Convert Unix timestamps to readable dates and generate timestamps from dates instantly in your browser.",
        "keywords": [
            "unix timestamp converter",
            "epoch converter",
            "timestamp to date",
        ],
        "how_to": [
            "Paste a Unix timestamp or pick a date and time.",
            "Convert it to readable local time and UTC.",
            "Use the reverse conversion when you need a fresh timestamp.",
        ],
        "faq": [
            (
                "Does it support milliseconds?",
                "Yes. It can detect common 10-digit and 13-digit timestamps.",
            ),
            (
                "Which timezone is shown?",
                "The page shows both your local browser time and UTC.",
            ),
        ],
        "related": ["json-formatter", "jwt-decoder", "url-encoder"],
    },
    {
        "id": "image-to-base64",
        "slug": "image-to-base64",
        "title": "Image to Base64",
        "category": "image",
        "icon": "🖼",
        "type": "file",
        "summary": "Convert an image file into a Base64 data URL directly in your browser.",
        "seo_title": "Image to Base64 Converter Online - Private Browser Tool",
        "meta_description": "Convert PNG, JPG, or WebP images to Base64 data URLs without uploading files to a server.",
        "keywords": ["image to base64", "png to base64", "data url generator"],
        "how_to": [
            "Choose an image file from your device.",
            "Click convert to read it locally.",
            "Copy the Base64 data URL or download the text.",
        ],
        "faq": [
            (
                "Are my images uploaded?",
                "No. The file is read and processed inside your browser only.",
            ),
            (
                "Which formats work?",
                "Common browser image formats like PNG, JPG, GIF, and WebP work well.",
            ),
        ],
        "related": ["image-resizer", "base64-encoder", "base64-decoder"],
    },
    {
        "id": "image-resizer",
        "slug": "image-resizer",
        "title": "Image Resizer & Converter",
        "category": "image",
        "icon": "⬚",
        "type": "file",
        "summary": "Resize images and export them as PNG, JPG, or WebP on your device.",
        "seo_title": "Image Resizer Online - Resize and Convert Images in Browser",
        "meta_description": "Resize and convert images online without uploads. Output PNG, JPG, or WebP directly from your browser.",
        "keywords": ["image resizer", "resize image online", "jpg png webp converter"],
        "how_to": [
            "Select an image from your device.",
            "Choose output width, format, and quality.",
            "Generate the resized image and download it.",
        ],
        "faq": [
            (
                "Can I keep the aspect ratio?",
                "Yes. The tool maintains the original aspect ratio automatically.",
            ),
            (
                "Does it compress images too?",
                "Yes. JPG and WebP quality controls help reduce file size.",
            ),
        ],
        "related": ["image-to-base64", "slug-generator", "percentage-calculator"],
    },
    {
        "id": "gst-calculator",
        "slug": "gst-calculator",
        "title": "GST Calculator",
        "category": "calculators",
        "icon": "₹",
        "type": "calculator",
        "summary": "Calculate inclusive and exclusive GST amounts for common Indian tax rates.",
        "seo_title": "GST Calculator Online - Inclusive and Exclusive GST",
        "meta_description": "Calculate GST quickly with inclusive and exclusive price modes using common Indian GST rates.",
        "keywords": [
            "gst calculator",
            "inclusive gst calculator",
            "exclusive gst calculator",
        ],
        "how_to": [
            "Enter the amount and choose the GST rate.",
            "Pick whether your amount includes GST or excludes GST.",
            "See the tax amount and final total instantly.",
        ],
        "faq": [
            (
                "Which GST rates are supported?",
                "The calculator supports common rates like 5%, 12%, 18%, and 28%, plus a custom rate option.",
            ),
            (
                "Can I calculate reverse GST?",
                "Yes. Inclusive mode extracts GST from a tax-inclusive total.",
            ),
        ],
        "related": ["percentage-calculator", "emi-calculator", "timestamp-converter"],
    },
    {
        "id": "emi-calculator",
        "slug": "emi-calculator",
        "title": "EMI Calculator",
        "category": "calculators",
        "icon": "💳",
        "type": "calculator",
        "summary": "Estimate monthly EMIs for loans using principal, interest, and tenure.",
        "seo_title": "EMI Calculator Online - Monthly Loan EMI Estimator",
        "meta_description": "Calculate monthly loan EMI, total payment, and interest online with a clean simple browser tool.",
        "keywords": [
            "emi calculator",
            "loan emi calculator",
            "monthly installment calculator",
        ],
        "how_to": [
            "Enter loan amount, annual interest rate, and tenure in months.",
            "Click calculate EMI.",
            "Review EMI, total interest, and total repayment instantly.",
        ],
        "faq": [
            (
                "Is this suitable for home and personal loans?",
                "Yes. It is a simple EMI estimator for common reducing-balance loan scenarios.",
            ),
            (
                "Does it include fees?",
                "No. It calculates principal and interest only unless you add fees separately.",
            ),
        ],
        "related": ["gst-calculator", "percentage-calculator", "timestamp-converter"],
    },
    {
        "id": "percentage-calculator",
        "slug": "percentage-calculator",
        "title": "Percentage Calculator",
        "category": "calculators",
        "icon": "%",
        "type": "calculator",
        "summary": "Handle common percentage problems with one friendly calculator.",
        "seo_title": "Percentage Calculator Online - Fast Everyday Percentage Math",
        "meta_description": "Calculate X% of Y, percentage increase, decrease, and percentage difference quickly online.",
        "keywords": ["percentage calculator", "percent increase", "percent decrease"],
        "how_to": [
            "Choose the percentage mode you need.",
            "Enter the required values.",
            "Get a simple readable answer immediately.",
        ],
        "faq": [
            (
                "What calculations are included?",
                "The tool covers percent of a number, increase, decrease, and what percent one value is of another.",
            ),
            (
                "Is it good for discounts and markups?",
                "Yes. Use it for sale discounts, growth, and quick comparisons.",
            ),
        ],
        "related": ["gst-calculator", "emi-calculator", "slug-generator"],
    },
]

PAGES = [
    {
        "slug": "about",
        "title": "About",
        "content": "ToolMint was built for people who want small useful web tools that are fast, private, and easy to use. Most tools in this starter kit run fully in the browser, so users get quick results without uploads, accounts, or friction.",
    },
    {
        "slug": "privacy",
        "title": "Privacy Policy",
        "content": "This starter project is designed so most tools run locally in the visitor's browser.",
    },
    {
        "slug": "terms",
        "title": "Terms of Use",
        "content": "This website is provided as-is for general information and utility use. Always review financial calculations, transformed files, or generated outputs before relying on them for legal, business, or production work.",
    },
    {
        "slug": "contact",
        "title": "Contact",
        "content": "You can contact us at E-Mail :- rishibanota837@gmail.com. More socials will be added later.",
    },
]
